services:
  - type: web
    name: deia-trainer-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        value: deia-trainer-jwt-secret-key-2024
    autoDeploy: true

databases:
  - name: deia-trainer-db
    region: oregon
    plan: free